(require 'org)
(org-babel-tangle-file "spacemacs.org")
(setq byte-compile-warnings '(not free-vars unresolved noruntime lexical make-local))
(byte-compile-file "init.el")
(byte-compile-file "spacemacs-defaults.el")
(byte-compile-file "spacemacs-layers.el")
(byte-compile-file "spacemacs-init.el")
(byte-compile-file "user-config.el")
(byte-compile-file "user-init.el")
