#!/bin/bash

# Hacking utilities
PACKAGES="$PACKAGES \
	build-essential \
	\
	cpp-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-aarch64-linux-gnu \
	pkg-config-aarch64-linux-gnu \
	\
	gcc-arm-linux-gnueabi g++-arm-linux-gnueabi gcc-arm-linux-gnueabi \
	pkg-config-arm-linux-gnueabi \
	\
	gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf gcc-arm-linux-gnueabihf \
	pkg-config-arm-linux-gnueabihf \
	\
	gcc-arm-linux-androideabi \
	android-tools-adb android-tools-adbd android-tools-fastboot android-tools-fsutils \
	\
	colorgcc \
	autoconf automake libtool \
	cmake \
	premake4 \
	ccache \
	doxygen graphviz \
	byacc flex bison \
	ltrace strace \
	git gitk git-gui tig git-flow \
	cscope \
	mercurial \
	intel-gpu-tools \
	python \
	ruby ruby-dev \
	linaro-boot-utils linaro-image-tools \
	\
	qemu-system-x86 qemu-system-arm qemu-system-aarch64 \
	qemu-launcher qemuctl \
"

# 32bit tools
PACKAGES="$PACKAGES \
	libncurses5:i386 \
"

# Text tools and utilties
PACKAGES="$PACKAGES \
	vim-nox \
	texinfo \
	texlive-latex-base texlive-latex-recommended texlive-latex-extra \
	texlive-fonts-recommended \
	texlive-lang-english texlive-lang-italian \
	latex-beamer \
	latex-make latex-mk latexmk \
	vim-latexsuite \
"

# Unix utils
PACKAGES="$PACKAGES \
	zsh \
	aterm screen tmux terminator \
	gawk sed moreutils \
	ranger autojump bc \
	htop iotop hwloc pv \
	powertop \
	x11-xserver-utils arandr xdotool xsel \
	usbutils \
	smartmontools \
	sysfsutils \
	tree \
	figlet \
	inxi \
	hexdump ghex \
	ttyrec \
"
# hwloc => lstopo|hwloc-ls
# x11-xserver-utils => xrandr
# sysfsutils => systool
# inxi => inxi -v4 -c6 OR inxi -bDc 6

# GNOME utils
PACKAGES="$PACKAGES \
	nautilus-actions \
	nautilus-compare \
	nautilus-emblems \
	nautilus-filename-repairer \
	nautilus-gtkhash \
	nautilus-ideviceinfo \
	nautilus-image-converter \
	nautilus-image-manipulator \
	nautilus-open-terminal \
	nautilus-pastebin \
	nautilus-qdigidoc \
	nautilus-script-audio-convert \
	nautilus-scripts-manager \
	nautilus-sendto \
	nautilus-share \
	nautilus-wipe \
"

# Networking libraries
PACKAGES="$PACKAGES \
	iproute iptables netcat-openbsd rsync tcpdump nmap \
	openssh-client openssh-server \
	mutt msmtp offlineimap imapfilter ldap-utils \
	irssi \
	curl wget axel \
	links2 \
	transmission \
	uml-utilities\
"
# uml-utilities => tunctl

# Multimedia libraries
PACKAGES="$PACKAGES \
	smplayer sox \
	gimp gimp-data-extras gimp-flegita gimp-gutenprint \
	gimp-normalmap gimp-plugin-registry gimp-texturize \
	gcolor2 \
"

# Development libraries
PACKAGES="$PACKAGES \
	ncurses-dev \
"

# Archive utilities
PACKAGES="$PACKAGES \
	atool unrar \
"

# Python packages
PACKAGES="$PACKAGES \
	python-dev \
	python-matplotlib \
	python-scipy \
	python-pip \
	python-gnomekeyring \
	python-sqlite \
"

echo
echo
echo "Adding Linaro PPA"
echo
sudo add-apt-repository ppa:linaro-maintainers/tools

echo
echo
echo "Additional packages to be installed: "
echo $PACKAGES
echo
echo

sudo apt-get update
sudo apt-get install aptitude
sudo aptitude install $PACKAGES

# Restart nautilus session to enable extensions
nautilus -q

